<?php

 // Auto generated by wpfluent Installer.

 return array (
  'name' => 'FluentCart Elementor Blocks',
  'slug' => 'fluentcartelementorblocks',
  'domain_path' => '/language',
  'text_domain' => 'fluent-cart-elementor-blocks',
  'hook_prefix' => 'fluentcartelementorblocks',
  'rest_version' => 'v2',
  'env' => 'dev',
);
